export const citiesByState = {
  "Andhra Pradesh": [
    "Adoni",
    "Amaravati",
    "Anantapur",
    "Bhimavaram",
    "Chittoor",
    "Eluru",
    "Guntur",
    "Hindupur",
    "Kadapa",
    "Kakinada",
    "Kurnool",
    "Machilipatnam",
    "Nandyal",
    "Narasaraopet",
    "Nellore",
    "Ongole",
    "Proddatur",
    "Rajahmundry",
    "Srikakulam",
    "Tadepalligudem",
    "Tenali",
    "Tirupati",
    "Visakhapatnam",
    "Vizianagaram",
  ],

  "Arunachal Pradesh": [
    "Bomdila",
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Roing",
    "Tawang",
    "Tezu",
    "Ziro",
  ],

  Assam: [
    "Barpeta",
    "Bongaigaon",
    "Dhubri",
    "Dibrugarh",
    "Golaghat",
    "Guwahati",
    "Jorhat",
    "Karimganj",
    "Lakhimpur",
    "Nagaon",
    "Silchar",
    "Sivasagar",
    "Tezpur",
    "Tinsukia",
  ],

  Bihar: [
    "Ara",
    "Begusarai",
    "Bhagalpur",
    "Bihar Sharif",
    "Buxar",
    "Chapra",
    "Darbhanga",
    "Gaya",
    "Hajipur",
    "Katihar",
    "Motihari",
    "Muzaffarpur",
    "Patna",
    "Purnia",
    "Samastipur",
    "Sasaram",
    "Siwan",
  ],

  Chhattisgarh: [
    "Ambikapur",
    "Bhilai",
    "Bilaspur",
    "Dhamtari",
    "Durg",
    "Jagdalpur",
    "Janjgir",
    "Korba",
    "Kawardha",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
  ],
  Delhi: [
    "Central Delhi",
    "Dwarka",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "Rohini",
    "South Delhi",
    "West Delhi",
  ],

  Goa: [
    "Bicholim",
    "Curchorem",
    "Mapusa",
    "Margao",
    "Panaji",
    "Ponda",
    "Valpoi",
    "Vasco da Gama",
  ],

  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Bharuch",
    "Bhavnagar",
    "Bhuj",
    "Gandhinagar",
    "Godhra",
    "Jamnagar",
    "Junagadh",
    "Mehsana",
    "Morbi",
    "Navsari",
    "Palanpur",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Surat",
    "Surendranagar",
    "Vadodara",
    "Valsad",
    "Veraval",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Baramulla",
    "Budgam",
    "Jammu",
    "Kathua",
    "Kupwara",
    "Pulwama",
    "Shopian",
    "Sopore",
    "Srinagar",
    "Udhampur",
  ],

  Haryana: [
    "Ambala",
    "Bahadurgarh",
    "Bhiwani",
    "Faridabad",
    "Fatehabad",
    "Gurgaon or Gurugram",
    "Hisar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Dharamshala",
    "Hamirpur",
    "Kangra",
    "Kullu",
    "Manali",
    "Mandi",
    "Nahan",
    "Palampur",
    "Shimla",
    "Solan",
    "Una",
  ],

  Jharkhand: [
    "Bokaro",
    "Chaibasa",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "Giridih",
    "Hazaribagh",
    "Jamshedpur",
    "Lohardaga",
    "Medininagar",
    "Ramgarh",
    "Ranchi",
  ],

  Karnataka: [
    "Bagalkot",
    "Bangalore or Bengaluru",
    "Belgaum",
    "Bellary",
    "Bidar",
    "Bijapur",
    "Chikkamagaluru",
    "Davanagere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Hubli",
    "Kalaburagi",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mangalore",
    "Mysore",
    "Raichur",
    "Shivamogga",
    "Tumkur",
    "Udupi",
    "Vijayapura",
    "Yadgir",
  ],

  Kerala: [
    "Alappuzha",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kochi",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  Ladakh: ["Kargil", "Leh"],

  Lakshadweep: ["Agatti", "Amini", "Andrott", "Kavaratti", "Minicoy"],

  "Madhya Pradesh": [
    "Bhopal",
    "Burhanpur",
    "Chhindwara",
    "Dewas",
    "Guna",
    "Gwalior",
    "Hoshangabad",
    "Indore",
    "Jabalpur",
    "Katni",
    "Khandwa",
    "Mandsaur",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Shivpuri",
    "Singrauli",
    "Ujjain",
    "Vidisha",
  ],

  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Bhiwandi",
    "Chandrapur",
    "Dhule",
    "Ichalkaranji",
    "Jalgaon",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mira-Bhayandar",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Navi Mumbai",
    "Panvel",
    "Parbhani",
    "Pune",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Solapur",
    "Thane",
    "Ulhasnagar",
    "Vasai-Virar",
    "Wardha",
    "Yavatmal",
  ],

  Manipur: [
    "Bishnupur",
    "Churachandpur",
    "Imphal",
    "Kakching",
    "Thoubal",
    "Ukhrul",
  ],

  Meghalaya: ["Jowai", "Nongpoh", "Shillong", "Tura", "Williamnagar"],

  Mizoram: ["Aizawl", "Champhai", "Kolasib", "Lunglei", "Serchhip"],

  Nagaland: ["Dimapur", "Kohima", "Mokokchung", "Tuensang", "Wokha"],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore",
    "Baripada",
    "Berhampur",
    "Bhadrak",
    "Bhubaneswar",
    "Boudh",
    "Cuttack",
    "Dhenkanal",
    "Jajpur",
    "Jeypore",
    "Jharsuguda",
    "Kendrapara",
    "Keonjhar",
    "Koraput",
    "Paradeep",
    "Puri",
    "Rayagada",
    "Rourkela",
    "Sambalpur",
    "Sundargarh",
  ],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  Punjab: [
    "Abohar",
    "Amritsar",
    "Barnala",
    "Batala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Firozpur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Khanna",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Mohali",
    "Muktsar",
    "Nawanshahr",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sangrur",
    "Tarn Taran",
  ],

  Rajasthan: [
    "Abu Road",
    "Ajmer",
    "Alwar",
    "Balotra",
    "Baran",
    "Barmer",
    "Beawar",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Kishangarh",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Sawai Madhopur",
    "Sikar",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],

  Sikkim: ["Gangtok", "Geyzing", "Mangan", "Namchi", "Pakyong", "Singtam"],

  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Hosur",
    "Kanchipuram",
    "Kanyakumari",
    "Karur",
    "Madurai",
    "Mayiladuthurai",
    "Nagercoil",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Salem",
    "Sivagangai",
    "Sivakasi",
    "Tenkasi",
    "Thanjavur",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Villupuram",
    "Virudhunagar",
  ],

  Telangana: [
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hyderabad",
    "Jagtial",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Kodad",
    "Mahabubabad",
    "Mahabubnagar",
    "Mancherial",
    "Medak",
    "Miryalaguda",
    "Nagarkurnool",
    "Nalgonda",
    "Nirmal",
    "Nizamabad",
    "Ramagundam",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Warangal",
  ],

  Tripura: [
    "Agartala",
    "Ambassa",
    "Belonia",
    "Dharmanagar",
    "Kailashahar",
    "Khowai",
    "Sabroom",
    "Udaipur",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Amroha",
    "Ayodhya",
    "Azamgarh",
    "Badaun",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Bulandshahr",
    "Chandauli",
    "Deoria",
    "Etah",
    "Etawah",
    "Faizabad",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Greater Noida",
    "Hapur",
    "Hardoi",
    "Hathras",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur",
    "Kasganj",
    "Kaushambi",
    "Lakhimpur",
    "Lalitpur",
    "Lucknow",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Noida",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj or Allahabad",
    "Raebareli",
    "Rampur",
    "Saharanpur",
    "Sambhal",
    "Shahjahanpur",
    "Shamli",
    "Sitapur",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],

  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Champawat",
    "Dehradun",
    "Haldwani",
    "Haridwar",
    "Kashipur",
    "Kotdwar",
    "Mussoorie",
    "Nainital",
    "Pauri",
    "Pithoragarh",
    "Ramnagar",
    "Rishikesh",
    "Roorkee",
    "Rudraprayag",
    "Rudrapur",
    "Tehri",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],

  "West Bengal": [
    "Alipurduar",
    "Asansol",
    "Baharampur",
    "Bankura",
    "Bardhaman",
    "Barrackpore",
    "Darjeeling",
    "Durgapur",
    "Haldia",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Kharagpur",
    "Kolkata",
    "Krishnanagar",
    "Malda",
    "Midnapore",
    "Purulia",
    "Raiganj",
    "Siliguri",
  ],
};
