spring.application.name=foodiesApi

#mongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/instantMeal
spring.data.mongodb.database=instantMeal

#aws s3 configuration
#aws.access.key=${AWS_ACCESS_KEY}
#aws.secret.key=${AWS_SECRET_KEY}
#aws.region= ap-southeast-2
#aws.s3.bucketname=instant-meal

#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG

jwt.secret.key=RIM9y1T9rjlVxNYleXcyCCuRObuG0j4qriBGKrbUGgN

#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}