spring.application.name=foodiesApi

# MongoDB
spring.mongodb.uri=${MONGODB_URI}

# JWT
jwt.secret.key=${JWT_SECRET_KEY}

# Razorpay
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}

#AWS s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region= ap-southeast-2
aws.s3.bucketname=instant-meal

# Logging
#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG